export const ADD_MESSAGE = "ADD_MESSAGE"
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
export const ADD_USER = "ADD_USER"
export const USERS_LIST = "USERS_LIST"
export const UPDATE_MESSAGE_STATUS = 'UPDATE_MESSAGE_STATUS'
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";